(()=>{const state={lang:localStorage.getItem("molei-lang")||"en",methodFilter:"all",showAllMethods:false};const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];const t=p=>p.split(".").reduce((o,k)=>o?.[k],I18N[state.lang])??p;const loc=v=>typeof v==="string"?v:(v?.[state.lang]||v?.en||v?.zh||"");function roleClass(k){if(["soleFirst","coFirst"].includes(k))return"first";if(["soleCorr","coCorr"].includes(k))return"corresponding";if(["soleFirstCorr","coFirstSoleCorr","coFirstCoCorr"].includes(k))return"both";return""}const roleBadge=k=>`<span class="role-badge ${roleClass(k)}">${t(`roles.${k}`)}</span>`;
function renderI18N(){document.documentElement.lang=state.lang==="zh"?"zh-CN":"en";$("#lang-button").textContent=state.lang==="en"?"中文":"EN";$$('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));renderResearch();renderMethods();renderCollaborations();renderPreprints();renderPeople();renderTimeline()}
function renderResearch(){$("#research-grid").innerHTML=RESEARCH.map((x,i)=>`<article class="research-card"><span class="research-number">${String(i+1).padStart(2,"0")}</span><h3>${loc(x.title)}</h3><p>${loc(x.text)}</p></article>`).join("")}
function renderMethodFilters(){const ks=["all","transfer","inference","semisup","robust"];$("#method-filters").innerHTML=ks.map(k=>`<button class="filter-button ${state.methodFilter===k?"active":""}" data-filter="${k}" type="button">${t(`methodology.filters.${k}`)}</button>`).join("");$$('[data-filter]',$("#method-filters")).forEach(b=>b.addEventListener("click",()=>{state.methodFilter=b.dataset.filter;renderMethods()}))}
function pubRow(p,statusKey=null){return`<article class="pub-row"><div class="pub-year">${p.year}</div><div><h3 class="pub-title">${p.title}</h3><p class="pub-authors">${p.authors}</p><p class="pub-venue">${p.venue}</p></div><div class="pub-meta">${p.journal?`<span class="venue-badge">${p.journal}</span>`:""}${statusKey?`<span class="status-badge">${t(`status.${statusKey}`)}</span>`:""}${roleBadge(p.roleKey)}</div></article>`}
function renderMethods(){renderMethodFilters();const rows=METHODOLOGY.filter(p=>(state.methodFilter==="all"||p.topic===state.methodFilter)&&(state.showAllMethods||p.selected));$("#methodology-list").innerHTML=rows.map(p=>pubRow(p)).join("");$("#method-toggle").textContent=state.showAllMethods?t("methodology.showSelected"):t("methodology.showAll")}
function renderCollaborations(){$("#collaboration-list").innerHTML=COLLABORATIONS.map(p=>`<article class="featured-card"><div class="featured-top"><span class="journal-name">${p.journal}</span>${roleBadge(p.roleKey)}</div><h3>${p.title}</h3><p>${p.authors}</p><p>${p.venue}</p></article>`).join("")}
function renderPreprints(){$("#preprint-list").innerHTML=PREPRINTS.map(p=>pubRow(p,p.statusKey)).join("")}
function personCard(p){const img=p.photo||"assets/images/people/placeholder.svg";const links=[p.email?`<a href="mailto:${p.email}">Email</a>`:"",p.homepage?`<a href="${p.homepage}" target="_blank" rel="noopener">${t("people.homepage")}</a>`:""].filter(Boolean).join("");return`<article class="person-card"><img src="${img}" alt="${loc(p.name)}" loading="lazy"><div class="person-body"><strong>${loc(p.name)}</strong><span>${loc(p.role)}</span>${p.interests?`<p>${loc(p.interests)}</p>`:""}${links?`<div class="person-links">${links}</div>`:""}</div></article>`}
function renderPeople(){const gs=["postdoc","phd","master"];$("#people-groups").innerHTML=gs.map(g=>{const ms=PEOPLE[g]||[];return`<section class="people-group"><h3>${t(`people.groups.${g}`)}</h3><div class="people-grid">${ms.length?ms.map(personCard).join(""):`<div class="people-empty">${t("people.empty")}</div>`}</div></section>`}).join("")}
function renderTimeline(){$("#timeline").innerHTML=TIMELINE.map(x=>`<div class="timeline-item"><span class="timeline-date">${loc(x.date)}</span><div><strong>${loc(x.title)}</strong><p>${loc(x.detail)}</p></div></div>`).join("")}
$("#lang-button").addEventListener("click",()=>{state.lang=state.lang==="en"?"zh":"en";localStorage.setItem("molei-lang",state.lang);renderI18N()});$("#method-toggle").addEventListener("click",()=>{state.showAllMethods=!state.showAllMethods;renderMethods()});$("#menu-button").addEventListener("click",()=>{const n=$("#nav-links"),open=n.classList.toggle("open");$("#menu-button").setAttribute("aria-expanded",String(open))});$$('#nav-links a').forEach(a=>a.addEventListener("click",()=>{$("#nav-links").classList.remove("open");$("#menu-button").setAttribute("aria-expanded","false")}));$("#year").textContent=new Date().getFullYear();renderI18N()})();
